Document: srelay
Title: Debian srelay Manual
Author: <insert document author here>
Abstract: This manual describes what srelay is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/srelay/srelay.sgml.gz

Format: postscript
Files: /usr/share/doc/srelay/srelay.ps.gz

Format: text
Files: /usr/share/doc/srelay/srelay.text.gz

Format: HTML
Index: /usr/share/doc/srelay/html/index.html
Files: /usr/share/doc/srelay/html/*.html
